### ISSUE TITLE
Pawoo is...blocked?

### ISSUE THREAD

**Issue by hakusaro** [tootcafe/blocked-instances#13]
I suppose this is a spin off of [this toot](https://toot.cafe/users/nolan/updates/10664) and [this toot](https://pawoo.net/@hakusaro/4038336), because clearly pawoo.net is listed as a blocked instance and yet we're still able to talk (which is nice, because I'd much prefer to live on an instance backed by a big provider like Pixiv than anyone else (but that's just me)).

So...maybe this is a mastodon bug? Or maybe direct user to user interaction is still permitted (while natural things from the federated timeline are brought in)?

**Comment by hakusaro** [comment]
A personal aside: So you learn about Mastodon on some random site and decide to pick a server with a huge amount of users on the pretense that it _probably won't be blackballed by other servers_ and it does, which is kinda hilarious.

I considered opening an issue on the mastodon repo, but the issue template was unclear as to how to ask a question,...

**Comment by nolanlawson** [comment]
I think this may be a bug. Also perhaps I should reconsider about pawoo.net anyway. At the beginning there were some worries that they had a problem with sexualized depictions of children, but maybe they've managed to stamp that out. I'll re-evaluate later, but for now yes our admin instance says they are "suspended" so I don't know why they appear to be unblocked.

**Comment by hakusaro** [comment]
As unsavory as loli is, it's permitted in Japan. That being said, they do have rules that say any loli has to be behind a content warning.

Maybe we should file a bug report on mastodon about this?

**Comment by nolanlawson** [comment]
I have re-suspended them and hopefully everything is okay now. If you still see pawoo.net posts, then yeah it is probably a bug in Mastodon.

And I don't believe it's relevant if it's legal in Japan or not; it's distasteful to a lot of people and is illegal in countries like Canada as well as being a gray zone in the US, so I would prefer to ban it and reject media files.
