### ISSUE TITLE
Another term for Free speech zone

### ISSUE THREAD

**Issue by Shnoulle** [tootcafe/blocked-instances#15]
See [Free speech zone](https://en.wikipedia.org/wiki/Free_speech_zone) . 

Don't let hater people take this term only for us. Use directly `Nazism promotion` .

**Comment by nolanlawson** [comment]
Thanks for the suggestion, but I am trying to be diplomatic about this. I have issues with the name too, but this seems to be the name that incenses the least number of people. FWIW that is basically why I disallow them; our instance explicitly disallows promotion of National Socialism.

**Comment by Shnoulle** [comment]
Then just for remind 

> Many colleges and universities earlier instituted free speech zone rules during the Vietnam-era protests of the 1960s and 1970s.

**Comment by sigmap** [comment]
I think those laws were to curtail the protests of Americas involvement in Vietnam by positioning protests and protesters out of sight of the public and media. At least in states. Interesting how censorship cuts both ways like that. But I suppose it's alright when it's speech you don't like.

**Comment by Chootin** [comment]
What about "Unmoderated Speech Zone"? I can't imagine anyone having an issue with that.
