### ISSUE TITLE
gorf.club silence

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [tootcafe/blocked-instances#21]
hey, owner of gorf.club here

wondering why gorf club has been added to the list. i've only ever had like a maximum of 5 users and right now i'm probably the only user. i really dislike all of the instances with nazis and lolicon etc. and haven't had any of that stuff on my instance afaik

**Comment by berrythesoftwarecodeprogrammar** [comment]
hmm i see that this page from the references lists gorf.club as 'defunct': http://telegra.ph/Instances-to-silencesuspend-on-Mastodon-06-23

could be that there was an issue until recently between my server and mastodon instances. i fixed it like a week ago though

**Comment by nolanlawson** [comment]
Sorry, I looked over the terms of service / code of conduct and I don't feel it's strict enough for full federation with toot.cafe. OTOH I can't find a strong reason to suspend, so I'm going to stick with silencing for now. Thanks for understanding.
