### ISSUE TITLE
Consolidation

### ISSUE THREAD

**Issue by danmademe** [tootcafe/blocked-instances#8]
Would you be willing to consolidate this list with the one I made ? I want to make a GitHub org with a single repo which maintains a blocklist. 

With other instance admins as members of the org whom can act as reviewers for pull requests. 

https://github.com/MastodonBlocklist/blocklist

**Comment by danmademe** [comment]
I think that If something like this was to work it needs to not be associated to a single instance. But be maintained by a group of trusted peers.

**Comment by nolanlawson** [comment]
Thanks for the offer! I think for the time being, though, I'd prefer to just keep this for toot.cafe and not share with other admins. I'm a bit worried about this becoming a global scarlet letter for all of Mastodon, when for me it's more a way to communicate the values of my own instance and report what I'm seeing as I handle reports.  I'll probably take a look at your list and maybe borrow some, though! 😁
