### ISSUE TITLE
rainbowdash.net does not actually federate with Mastodon

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/blocked-instances#9]
I've seen this murmured about before, but in [this toot](https://plateia.org/notice/9807) it's explicitly stated that rainbowdash.net doesn't actually federate with Mastodon. Needs verification, but if true, we can remove it from the list.

**Comment by mkody** [comment]
I did get at least two users in the federated timeline when I was using mastodon.social.

**Comment by nolanlawson** [comment]
Hm OK so apparently there may be some way around it or it's not quite accurate to say it doesn't federate. In any case there's no harm in keeping it on the list AFAICT. Thanks!
